version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "config-copy-stack"
s3_bucket = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "SourceBucketArn=\"arn:aws:s3:::aws-controltower-logs-030388951625-us-east-1\" AccountList=\"030388951625,242085006133,683573700852\" RegionList=\"us-east-1,eu-west-1,us-east-2,us-west-2\" SourceAccountId=\"030388951625\""
s3_prefix = "config-copy-stack"
region = "us-east-1"
image_repositories = []
disable_rollback = true

